name: ChatGPT Python YAML generator

on:
  push:
    branches: [ "master", "pavantest" ]
  pull_request:
    branches: [ "master", "pavantest" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags:  pavangudiwada/chatgpttestrep:latest